In [24]:
# Import required libraries
import sys
import numpy as np
from scipy.optimize import linprog
np.set_printoptions(threshold=sys.maxsize)

# Problem 4 a)

In [28]:
# Set the inequality constraints matrix
# Note: the inequality constraints must be in the form of <=
#A = np.array([[-1, -1, -1], [-1, 2, 0], [0, 0, -1], [-1, 0, 0], [0, -1, 0], [0, 0, -1]])
A = np.zeros(shape=(40, 12))

for i in range(40):
    A[i,i//4]=-1
    if (i//2)%2==0:
        if (i%2==0):
            A[i,10]=-1
        else:
            A[i,11]=-1
    else:
        if(i%2==0):
            A[i,10]=1
        else:
            A[i,11]=1
    #A[i,i+12]=-1

print(A)

[[-1.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [-1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1.]
 [-1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [-1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0. -1.  0.  0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1.]
 [ 0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  

In [30]:
from numpy import genfromtxt
X_old = genfromtxt('a4.csv', delimiter=',')
X = X_old.T 
print(X)

# Set the inequality constraints vector
#b = np.array([-1000, 0, -340, 0, 0, 0])
b = np.zeros(shape=(40))
for i in range(40):
    if (i//2)%2==0:
        if (i%2==0):
            b[i]=-X[i//4,0]
        else:
            b[i]=-X[i//4,1]
    else:
        if(i%2==0):
            b[i]=X[i//4,0]
        else:
            b[i]=X[i//4,1]

print(b)


# Set the coefficients of the linear objective function vector
#c = np.array([10, 15, 25])
c = np.zeros(shape=(12))
for i in range(10):
    c[i]=1

print(c)
    
# Solve linear programming problem
res = linprog(c, A_ub=A, b_ub=b)

# Print results
print('Optimal value:', round(res.fun, ndigits=2),
      '\nx values:', res.x,
      '\nNumber of iterations performed:', res.nit,
      '\nStatus:', res.message)

[[ 0.074984  -0.37907    1.       ]
 [-0.33575   -0.84075    1.       ]
 [ 0.11657   -0.166      1.       ]
 [-0.44398   -0.38495   -1.       ]
 [ 0.82067    0.39792    1.       ]
 [ 0.0032261  0.026432  -1.       ]
 [-0.10646    0.73267   -1.       ]
 [-0.2222     0.26439   -1.       ]
 [ 0.28111   -0.33193    1.       ]
 [-0.46789    0.37675   -1.       ]]
[-0.074984   0.37907    0.074984  -0.37907    0.33575    0.84075
 -0.33575   -0.84075   -0.11657    0.166      0.11657   -0.166
  0.44398    0.38495   -0.44398   -0.38495   -0.82067   -0.39792
  0.82067    0.39792   -0.0032261 -0.026432   0.0032261  0.026432
  0.10646   -0.73267   -0.10646    0.73267    0.2222    -0.26439
 -0.2222     0.26439   -0.28111    0.33193    0.28111   -0.33193
  0.46789   -0.37675   -0.46789    0.37675  ]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
Optimal value: 4.47 
x values: [3.79070004e-01 8.40750004e-01 1.66000004e-01 4.43980000e-01
 8.20670000e-01 2.64319960e-02 7.32669996e-01 2.64389996e-01
 3.31930004e-

# Problem 4b)

In [35]:
# Set the inequality constraints matrix
# Note: the inequality constraints must be in the form of <=
#A = np.array([[-1, -1, -1], [-1, 2, 0], [0, 0, -1], [-1, 0, 0], [0, -1, 0], [0, 0, -1]])
A = np.zeros(shape=(16,8))
A[0,0] = 0.8147
A[0,1] = 0.6324 
A[0,2] = 0.9575 
A[0,3] = 0.9572
A[1,0] = 0.9058 
A[1,1] = 0.0975 
A[1,2] = 0.9649 
A[1,3] = 0.4854
A[2,0] = 0.1270 
A[2,1] = 0.2785 
A[2,2] = 0.1576 
A[2,3] = 0.8003
A[3,0] = 0.9134 
A[3,1] = 0.5469 
A[3,2] = 0.9706 
A[3,3] = 0.1419

A[4,0] = -0.8147
A[4,1] = -0.6324 
A[4,2] = -0.9575 
A[4,3] = -0.9572
A[5,0] = -0.9058 
A[5,1] = -0.0975 
A[5,2] = -0.9649 
A[5,3] = -0.4854
A[6,0] = -0.1270 
A[6,1] = -0.2785 
A[6,2] = -0.1576 
A[6,3] = -0.8003
A[7,0] = -0.9134 
A[7,1] = -0.5469 
A[7,2] = -0.9706 
A[7,3] = -0.1419


for i in range(0,8):
    #A[8+i,i//4]=-1
    if (i%2==0):
        A[8+i,i//2]=1
        A[8+i,4+(i//2)]=-1
    else:
        A[8+i,i//2]=-1
        A[8+i,4+(i//2)]=-1

print(A)

[[ 0.8147  0.6324  0.9575  0.9572  0.      0.      0.      0.    ]
 [ 0.9058  0.0975  0.9649  0.4854  0.      0.      0.      0.    ]
 [ 0.127   0.2785  0.1576  0.8003  0.      0.      0.      0.    ]
 [ 0.9134  0.5469  0.9706  0.1419  0.      0.      0.      0.    ]
 [-0.8147 -0.6324 -0.9575 -0.9572  0.      0.      0.      0.    ]
 [-0.9058 -0.0975 -0.9649 -0.4854  0.      0.      0.      0.    ]
 [-0.127  -0.2785 -0.1576 -0.8003  0.      0.      0.      0.    ]
 [-0.9134 -0.5469 -0.9706 -0.1419  0.      0.      0.      0.    ]
 [ 1.      0.      0.      0.     -1.      0.      0.      0.    ]
 [-1.      0.      0.      0.     -1.      0.      0.      0.    ]
 [ 0.      1.      0.      0.      0.     -1.      0.      0.    ]
 [ 0.     -1.      0.      0.      0.     -1.      0.      0.    ]
 [ 0.      0.      1.      0.      0.      0.     -1.      0.    ]
 [ 0.      0.     -1.      0.      0.      0.     -1.      0.    ]
 [ 0.      0.      0.      1.      0.      0.      0.     -1. 

In [41]:


# Set the inequality constraints vector
#b = np.array([-1000, 0, -340, 0, 0, 0])
b = np.zeros(shape=(16))

b[0] = 0.4218
b[1] = 0.9157
b[2] = 0.7922
b[3] = 0.9595
b[4] = -0.4218
b[5] = -0.9157
b[6] = -0.7922
b[7] = -0.9595



print(b)


# Set the coefficients of the linear objective function vector
#c = np.array([10, 15, 25])
c = np.zeros(shape=(8))
for i in range(4,8):
    c[i]=1

print(c)
    
# Solve linear programming problem
res = linprog(c, A_ub=A, b_ub=b)

# Print results
print('Optimal value:', round(res.fun, ndigits=2),
      '\nx values:', res.x,
      '\nNumber of iterations performed:', res.nit,
      '\nStatus:', res.message)


[ 0.4218  0.9157  0.7922  0.9595 -0.4218 -0.9157 -0.7922 -0.9595  0.
  0.      0.      0.      0.      0.      0.      0.    ]
[0. 0. 0. 0. 1. 1. 1. 1.]
Optimal value: 1859450075770.35 
x values: [1.01049484e+00 9.08635867e-01 1.26290002e-01 8.93654994e-01
 4.76844375e+11 4.64570217e+11 4.49638533e+11 4.68396950e+11] 
Number of iterations performed: 5 
Status: The algorithm terminated successfully and determined that the problem is infeasible.


In [43]:
from numpy.linalg import inv

A = np.zeros(shape=(4,4))
A[0,0] = 0.8147
A[0,1] = 0.6324 
A[0,2] = 0.9575 
A[0,3] = 0.9572
A[1,0] = 0.9058 
A[1,1] = 0.0975 
A[1,2] = 0.9649 
A[1,3] = 0.4854
A[2,0] = 0.1270 
A[2,1] = 0.2785 
A[2,2] = 0.1576 
A[2,3] = 0.8003
A[3,0] = 0.9134 
A[3,1] = 0.5469 
A[3,2] = 0.9706 
A[3,3] = 0.1419
b = np.zeros(shape=(4))

b[0] = 0.4218
b[1] = 0.9157
b[2] = 0.7922
b[3] = 0.9595


print(np.matmul(inv(A),b))


[ 17.26784891   0.83836457 -15.8930473    1.08764577]


# Problem 4 c)

In [44]:
# Set the inequality constraints matrix
# Note: the inequality constraints must be in the form of <=
#A = np.array([[-1, -1, -1], [-1, 2, 0], [0, 0, -1], [-1, 0, 0], [0, -1, 0], [0, 0, -1]])
A = np.zeros(shape=(40, 22))

for i in range(40):
    if (i//2)%2==0:
        if i%2==0:
            A[i,0]=-1
        else:
            A[i,0]=1
    else:
        if i%2==0:
            A[i,1]=-1
        else:
            A[i,1]=1    
    A[i,2+(i//2)]=-1

print(A)

[[-1.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.]
 [ 1.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.]
 [ 0. -1.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.]
 [ 0.  1.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.]
 [-1.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.]
 [ 1.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.]
 [-1.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0. 

In [48]:
from numpy import genfromtxt
X_old = genfromtxt('a4.csv', delimiter=',')
X = X_old.T 
print(X)

# Set the inequality constraints vector
#b = np.array([-1000, 0, -340, 0, 0, 0])
b = np.zeros(shape=(40))
for i in range(40):
    if (i//2)%2==0:
        if i%2==0:
            b[i] = X[i//4,0]
        else:
            b[i] = -X[i//4,0]        
    else:
        if i%2==0:
            b[i] = X[i//4,1]
        else:
            b[i] = -X[i//4,1]

print(b)



# Set the coefficients of the linear objective function vector
#c = np.array([10, 15, 25])
c = np.zeros(shape=(22))
for i in range(2,22):
    c[i]=1

print(c)

# Solve linear programming problem
res = linprog(c, A_ub=A, b_ub=b)

# Print results
print('Optimal value:', round(res.fun, ndigits=2),
      '\nx values:', res.x,
      '\nNumber of iterations performed:', res.nit,
      '\nStatus:', res.message)


[[ 0.074984  -0.37907    1.       ]
 [-0.33575   -0.84075    1.       ]
 [ 0.11657   -0.166      1.       ]
 [-0.44398   -0.38495   -1.       ]
 [ 0.82067    0.39792    1.       ]
 [ 0.0032261  0.026432  -1.       ]
 [-0.10646    0.73267   -1.       ]
 [-0.2222     0.26439   -1.       ]
 [ 0.28111   -0.33193    1.       ]
 [-0.46789    0.37675   -1.       ]]
[ 0.074984  -0.074984  -0.37907    0.37907   -0.33575    0.33575
 -0.84075    0.84075    0.11657   -0.11657   -0.166      0.166
 -0.44398    0.44398   -0.38495    0.38495    0.82067   -0.82067
  0.39792   -0.39792    0.0032261 -0.0032261  0.026432  -0.026432
 -0.10646    0.10646    0.73267   -0.73267   -0.2222     0.2222
  0.26439   -0.26439    0.28111   -0.28111   -0.33193    0.33193
 -0.46789    0.46789    0.37675   -0.37675  ]
[0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Optimal value: 6.77 
x values: [0.06846211 0.07835797 0.14344611 0.30071203 0.26728789 0.76239203
 0.18503211 0.08764203 0.37551789 0.306